#' NMU Assessment Format
#'
#' Format for creating NMU-branded assessments including tests, assignments,
#' and exams with optional solutions mode.
#'
#' @param solutions \code{TRUE} to show solutions, \code{FALSE} to hide them
#' @param fig_width Default width (in inches) for figures
#' @param fig_height Default height (in inches) for figures
#' @param fig_crop \code{TRUE} to automatically apply the \code{pdfcrop} utility
#'   (if available) to pdf figures
#' @param fig_caption \code{TRUE} to render figures with captions
#' @param dev Graphics device to use for figure output (defaults to pdf)
#' @param df_print Method to be used for printing data frames. Valid values
#'   include "default", "kable", "tibble", and "paged". The "default" method
#'   uses a corresponding S3 method of \code{print}, typically
#'   \code{print.data.frame}. The "kable" method uses the
#'   \code{\link[knitr:kable]{knitr::kable}} function. The "tibble" method uses
#'   the \code{\link[tibble:formatting]{tibble}} package to print a summary of
#'   the data frame. The "paged" method creates a paginated HTML table (note
#'   that this method is only valid for formats that produce HTML). In addition
#'   to the named methods you can also pass an arbitrary function to be used
#'   for printing data frames. You can disable the \code{df_print} behavior
#'   entirely by setting the option \code{rmarkdown.df_print} to \code{FALSE}.
#'   See \link[rmarkdown]{df_print} for more information.
#' @param highlight Syntax highlighting style passed to Pandoc.
#'   Supported built-in styles include "default", "tango", "pygments", "kate",
#'   "monochrome", "espresso", "zenburn", "haddock", and "breezedark".
#'   Two custom styles are also included, "arrow", an accessible color scheme,
#'   and "rstudio", which mimics the default IDE theme. Alternatively, supply a
#'   path to a \samp{.theme} file to use
#'   \href{https://pandoc.org/MANUAL.html#syntax-highlighting}{a custom theme}.
#'   Pass \code{NULL} to prevent syntax highlighting.
#' @param keep_tex Keep the intermediate tex file used in the conversion to PDF.
#'   Note that this argument does not control whether to keep the auxiliary
#'   files (e.g., .aux) generated by LaTeX when compiling the tex file.
#' @param latex_engine LaTeX engine for producing PDF output. Options are
#'   "pdflatex", "lualatex", "xelatex" and "tectonic".
#' @param includes Named list of additional content to include within the
#'   document (typically created using the \code{\link{includes}} function).
#' @param md_extensions Markdown extensions to be added or removed from the
#'   default definition of R Markdown. See the \code{\link{rmarkdown_format}} for
#'   additional details.
#' @param output_extensions Pandoc extensions to be added or removed from the
#'   output format, e.g., \code{c("-smart", "+old_dashes")}.
#' @param pandoc_args Additional command line options to pass to pandoc
#' @param extra_dependencies A LaTeX dependency \code{latex_dependency()}, a
#'   list of LaTeX dependencies, a character vector of LaTeX package names
#'   (e.g., \code{c("framed", "hyperref")}), or a named list of LaTeX package
#'   options with the names being package names (e.g., \code{list(hyper =
#'   c("unicode=true", "breaklinks=true"), lmodern = NULL)}). It can be used to
#'   add custom LaTeX packages to the .tex header.
#' @param ... Additional arguments passed to \code{\link[rmarkdown]{pdf_document}}
#'
#' @return R Markdown output format to pass to \code{\link[rmarkdown]{render}}
#'
#' @examples
#' \dontrun{
#' library(rmarkdown)
#' render("input.Rmd", nmu_assessment(solutions = FALSE))
#' }
#'
#' @export
nmu_assessment <- function(solutions = FALSE,
                          fig_width = 6.5,
                          fig_height = 4.5,
                          fig_crop = TRUE,
                          fig_caption = TRUE,
                          dev = 'pdf',
                          df_print = "default",
                          highlight = "default",
                          keep_tex = FALSE,
                          latex_engine = "xelatex",
                          includes = NULL,
                          md_extensions = NULL,
                          output_extensions = NULL,
                          pandoc_args = NULL,
                          extra_dependencies = NULL,
                          ...) {
  
  # Get template path
  template_path <- system.file("rmarkdown/templates/nmu_assessment/resources/template.tex", 
                              package = "rmdNMU")
  
  # Get font directory
  font_dir <- system.file("fonts", package = "rmdNMU")
  
  # Create format
  rmarkdown::pdf_document(
    template = template_path,
    fig_width = fig_width,
    fig_height = fig_height,
    fig_crop = fig_crop,
    fig_caption = fig_caption,
    dev = dev,
    df_print = df_print,
    highlight = highlight,
    keep_tex = keep_tex,
    latex_engine = latex_engine,
    includes = includes,
    md_extensions = md_extensions,
    output_extensions = output_extensions,
    pandoc_args = c(pandoc_args, 
                   paste0("--variable=fontdir:", font_dir),
                   if (solutions) "--variable=params.solutions:true"),
    extra_dependencies = extra_dependencies,
    ...
  )
}